### PR TITLE
Add access keys for menubar

### PR DESCRIPTION
**Pull request by colemanw**
There have been a few suggestions to add accessKeys to make it eaiser to get to the menubar. This is the result.

- Add shortcut keys for the home menu ("M") and the quicksearch box ("Q").
- Improve the styling of the access keys help popup
- Actually show the correct modifier keys! (before it was hardcoded to Firefox on Win/Linux and incorrect for every other browser!)

screenshot from 2018-12-20 11-14-24

### CODE REVIEW

**Comment by colemanw** [comment]
@joemurray @aydun - thoughts?

**Comment by christianwach** [comment]
@colemanw Hmm, `alt + q` is a bit too close to `ctrl + q` for my liking - cue endless complaints from people saying that they've quit their browser instead of searching!

Might be worth clarifying in the popover text that on a Mac the combination of modifier keys that triggers access keys is `ctrl + alt` and therefore KAM implements `ctrl + alt + q` and `ctrl + alt + m` respectively. 

Also on a Mac, I keep hitting `alt + cmd + m` by accident, which minimises all my browser windows. And more than once now, I've accidentally hit `alt + cmd + q`, which quits the browser *and* closes all the windows. Safari has a "Reopen all windows from last session" option, but I can't find such a thing in Chrome.

I'm definitely in favour of access keys, I'm just not sure these work for me.

**Comment by colemanw** [comment]
@christianwach thanks I've updated the help bubble to show the right keys for Mac OS.

**Comment by christianwach** [comment]
> I've updated the help bubble to show the right keys for Mac OS.

@colemanw Thanks.

One more thing - on WordPress, when I hit `alt + m` it opens the "CiviCRM home" menu which then _appears_ to be active, but the menu element does not seem to _actually_ have focus - i.e. hitting `tab` does not continue to subsequent elements in the KAM menu but instead continues with elements elsewhere on the page.

**Comment by JoeMurray** [comment]
Trying to focus on where I can add value and not bikeshed, I've researched keyboard shortcuts in WCAG 2.0 and 2.1 and the main restriction is in WCAG 2.1 2.1.4 which has to do with shortcuts that don't use an Alt or Ctrl key. So I think these shortcuts are all compliant. @christianwach is making good points. I'll see about testing on a D8 install hopefully soon.

**Comment by JoeMurray** [comment]
Drupal 8, applied patch to core implementation.
Ctrl Alt M - worked
Ctrl Alt E - on Contact Summary view page, nothing happened
Ctrl Alt S - worked
Ctrl Alt N - this has problems. If used on some tabs it works at first (Contributions, Memberships, Events, Cases, Relationships, Notes; NOT Activities; I'm not sure if it is supposed to work on Groups and Tags but it doesn't, didn't test other tabs as not configured on our instance). After use on one tab without a page refresh eg just close the popup, if you switch tabs to another that notices it then try it seems to ignore the current tab and always brings up Add Relationship form.
Ctrl Alt Q - worked

**Comment by colemanw** [comment]
Christian, I've fixed the focus issue when activating a menu with an accesskey. Should be working well now.

Joe the other access keys you tested were already in core (`E`, `S` & `N`) and it doesn't look like they've gotten any love in quite a long time. Fixing them up would be nice but out-of-scope for this extension.

**Comment by christianwach** [comment]
> I've fixed the focus issue when activating a menu with an accesskey.

Confirmed here.

KAM is such a great improvement - thanks @colemanw @aydun for all the effort putting this together.

**Pull request merged**
