### PR TITLE
Close submenu on esc.

### PR DESCRIPTION
**Pull request by colemanw**
Fixes item number 8 on https://lab.civicrm.org/dev/accessibility/issues/1

### CODE REVIEW

**Comment by colemanw** [comment]
Ping @monishdeb

**Comment by monishdeb** [comment]
Tested, working fine. Here's a screencast:
after

Clicking on Esc on level 1 or level 2 sub-menu closes the current sub-menu and returns to parent menu unlike earlier where it closes all the sub-menus.

**Comment by monishdeb** [comment]
@colemanw @aydun can anyone of you please merge this PR?

**Comment by colemanw** [comment]
Closing per updated spec.

**Pull request closed without merging**
