### PR TITLE
Improve markup and css for WP

### PR DESCRIPTION
**Pull request by colemanw**
Overview
-----
Improves the menu styling across CMSs, but especially for WP.

Before
-----
Menu doesn't even appear in WP.

After
-----
Menu appears, and looks nice :)

### CODE REVIEW

**Comment by colemanw** [comment]
@christianwach I think you'll find this makes the menubar work well in WP without the admin tools plugin. Additional css tweaks you think are important would be welcome.

**Comment by colemanw** [comment]
@christianwach thanks for the feedback. The plan is indeed to move the code from this extension into core and remove the existing menubar plugin (which as you've noted is abysmal).

So I'd like to get on the same page with you about necessary vs pedantic styles. I think it's fine to keep things like color-scheme tweaks in your CAU plugin, but IMO since the code in this extension is soon to be core code, we need to ensure all the functional css is working - the menu has the correct height and the hamburger menu functions correctly are in the must-haves I believe, and I'd really welcome a PR from you if you've developed any code for those things.

**Comment by christianwach** [comment]
> I'd really welcome a PR from you if you've developed any code for those things.

Happy to help. Do you mean a PR on this repo?

**Comment by colemanw** [comment]
@christianwach see #20

**Pull request merged**
