### PR TITLE
#16: Backdrop burger tweaks

### PR DESCRIPTION
**Pull request by laryn**

### CODE REVIEW

**Comment by colemanw** [comment]
@laryn can you do a before/after screenshot?

**Comment by laryn** [comment]
Sure. I was mainly trying to make the hamburgers match size/weight more closely but tweaked background color to match the Backdrop admin menu, as shown here:

BEFORE
screen shot 2019-02-04 at 4 49 19 pm


AFTER
screen shot 2019-02-04 at 4 40 24 pm

**Comment by colemanw** [comment]
Hmm, it's very green. I would have thought white would match the admin bar icons better.

**Comment by laryn** [comment]
I'm okay with white, too, I suppose. My feeling was that it matched a
little too well in that regard as I saw at least three white hamburgers in
one view and I thought pulling out the green from the logo would help
individualize it while still being consistent in size/shape.

L.

**Comment by colemanw** [comment]
If you want it to look distinct I think we're better off keeping it as-is. That button might receive some style updates in the future which could conflict with the overrides you've done here. Devs are unlikely to notice this because not much testing happens on Backdrop.
Currently no other CMS-specific stylesheet overrides the look of this button so to keep things consistent I think we should close this for now.

**Pull request closed without merging**
