### PR TITLE
Configurable menubar position

### PR DESCRIPTION
**Pull request by colemanw**
Overview
----------
Adds a system setting to control menubar placement; works across the different CMSs.

screenshot from 2018-11-25 12-07-40

Background
------
There has been some discussion over the years about where the CiviCRM menubar should go, and different CMSs have gotten different treatment. Currently WP, Drupal & Backdrop get the menubar fixed to the top of the screen, obscuring the CMS admin menu. Some users think that's a good use of space, others find it annoying. Currently on Joomla the menubar is at the top of the content area and scrolls with the page; again with pros and cons.

In overhauling the menubar system and optimizing it for each CMS, I couldn't find one perfect solution that worked for every CMS, and even within a single CMS there may be different themes and admin interfaces which make menubar placement more complicated.

Technical details
-----------

Instead of one hardcoded position per CMS, we now have three options with the possibility of more.
As noted in the updated readme, the selected option becomes a css class added to the page body. The `CRM.menubar.initialize()` function places the menubar markup inside `#crm-container` instead of `body` if position is set to "Above Content Area". The stylesheet does the rest.
Since it wasn't possible to style this in a 100% generic way, an additional stylesheet is included for fine-tuning each CMS.

Notes
----------

This PR also improves styling of the mobile menu to make it look good on various CMSs. E.g. on Wordpress:

screenshot from 2018-11-25 12-27-51

### CODE REVIEW

**Comment by mattwire** [comment]
@vingle Configurable civicrm menu positions!

**Comment by vingle** [comment]
> @vingle Configurable civicrm menu positions!

Great solution — and works perfectly on Joomla.

**Comment by christianwach** [comment]
@colemanw What do I have to do to get the dropdown to show up?

**Comment by vingle** [comment]
> @colemanw What do I have to do to get the dropdown to show up?

did you go **Administer -> Customize Data & Screens -> Display Preferences**?

**Comment by christianwach** [comment]
Yep, option doesn't seem to be rendered:

screen shot 2018-11-26 at 11 48 40

**Comment by christianwach** [comment]
Nothing in the logs to suggest there's a problem.

**Comment by mattwire** [comment]
@christianwach Did you clear civicrm caches? ie. civicrm/clearcache  It's a new setting so won't show until that's done

**Comment by christianwach** [comment]
@mattwire Of course!

**Comment by mattwire** [comment]
@christianwach Check if Civi thinks the setting exists ('menubar_position') using the settings API. And looks like it's being added using a .extra.tpl so can you check if that is being included?

**Comment by colemanw** [comment]
@christianwach if you have any custom code on your site which already implements a `/CRM/Admin/Form/Preferences/Display.extra.tpl` then that could be the problem. That file is just a temporary hack until we get this migrated to core.

You can also set it with the api explorer:

screenshot from 2018-11-26 09-11-11

**Comment by colemanw** [comment]
@vingle thanks for testing on Joomla! Can you fill out that section of https://github.com/aydun/uk.squiffle.kam/issues/16 ?

**Comment by colemanw** [comment]
@vingle whoops you're right, my mistake. Fixed: b6830fc

**Comment by colemanw** [comment]
I'll merge this so there's no confusion about which branch to test when people engage with https://github.com/aydun/uk.squiffle.kam/issues/16

**Comment by christianwach** [comment]
Okay, so finally I got this working by upgrading to CiviCRM 5.9.alpha1 and uninstalling/reinstalling KAM. Simply couldn't get it to work with a simple upgrade.

I like the general idea of giving people the choice of where the menu appears. I'll have a go at refining the implementation when I get some free time. For example:

* The menu and element heights ought to be `32px` for desktop viewports and `46px` for viewports below `768px`. 
* The WordPress admin menu has `position: fixed` desktop viewports and `position: absolute` below `600px`. This should be respected or else we get this as we scroll: screen shot 2018-11-27 at 10 59 58
* I'm not sure that adding a `margin-top` to `#wpbody` is the best way to make space for the CiviCRM menu - it might be better to do what WordPress does and add extra `padding-top` to the `<html>` element and avoid the blank space above "Dashboard" in the left-hand menu: screen shot 2018-11-27 at 11 05 04


FWIW there are some other oddities, but I suspect they're inherent to Smart Menus itself. Here's what happens when I have a viewport that's not tall enough to hold the submenus:

screen shot 2018-11-27 at 10 51 02

As you can see, the items below "System Settings" disappear.

Having said all of the above, this is really nice work @colemanw and an excellent basis for future development! 👍

**Comment by colemanw** [comment]
@christianwach I think I've addressed your major concerns in #22.

**Pull request merged**
