### PR TITLE
Make spacebar to simulate click

### PR DESCRIPTION
**Pull request by monishdeb**
This PR covers 5th point of https://lab.civicrm.org/dev/accessibility/issues/1

Here's the screencast:
after

### CODE REVIEW

**Comment by monishdeb** [comment]
ping @colemanw

**Comment by colemanw** [comment]
This PR does 3 things, two of which I disagree with.

1. Spacebar opens the menu. I have no problem with that @monishdeb could you please open a new PR for just this item as it's not controversial.
2. Opens the quicksearch box when the page loads - I strongly disagree with this, as it could create all kinds of UX problems. I've already added a shortcut key for doing this by the way, so IMO quicksearch is already accessible from the keyboard at any time.
3. Keep them menu closed when hovering. I don't think this affects kbd accessibility one way or another, and open-on-hover is a nice feature IMO. Why disable it?

**Comment by monishdeb** [comment]
@JoeMurray @colemanw sorry about the 2nd fix to cover 9th item in https://lab.civicrm.org/dev/accessibility/issues/1. I earlier tried with tabindex=0, set to the first menu item i.e. quicksearch but that doesn't work on any CMSs. Alternatively, I thought of returning the first tab control always to quicksearch menu item on page load and I agree this approach will create UX problems. 

I will create a separate PR for 9th item.

**Comment by JoeMurray** [comment]
Coleman wrote: 

> Opens the quicksearch box when the page loads - I strongly disagree with this

There is no requirement in WCAG to do this. This was an erroneous implementation of the requirement that the menu be tabindex=0. 

@christianwach you're making a separate point, not about not opening searchbox by default, but about the precedence of different menus on a page.

The WCAG requirement is for the main menu on the page to be tabindex=0. Where a CMS integration has determined that a different menu is the main menu, then the CMS should if it is WCAG compliant set it with tabindex=0. I agree in these situations that Civi's menu should not have tabindex=0. However, the civi menu still in these situations for WCAG compliance a) has to be in the tabindex sequence and b) the order in the tabindex for the page needs to be a logical progression. 

What would be the proper way to go about implementing these WCAG requirements in the areas?

**Pull request merged**
